### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by chenhaoenen** [HelipengTony/eugrade#16]
hi， 厉害了！一个人撸项目！
我build docker的时候报错了，这是什么鬼？
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/49124360/204094169-61489ea2-697a-4775-b5fa-42e895e1168b.png">

**Comment by ttttonyhe** [comment]
@chenhaoenen Composer 阿里云镜像没有与官方源同步，你需要等待一段时间，或者降低依赖的版本:
- `lazer-database v2.0.1 => v2.0.0`
- `qiniu/php-sdk v7.8.0 =>v7.7.0`

PS. 这是个几年前的项目，没有维护了。如果你感兴趣的话可以帮忙维护，谢谢！

另外，你可能会遇到的几个问题：
- 站点地址都是写死在代码里的，需要自行更换或者设成环境变量
- NPM 依赖年久失修，安装过程可能会遇到问题
- 学生成绩功能图表设计没过脑子，你需要重新设计它

**Comment by chenhaoenen** [comment]
ok, 感谢大佬！感谢感谢
